[package]
name = "arcdps_log_tools"
version = "0.2.0"
edition = "2021"
authors = ["Zerthox"]
description = "Extract information from ArcDPS EVTC log files."

[dependencies]
arcdps_parse = { git = "https://github.com/zerthox/arcdps-bindings", features = ["serde"] }
clap = { version = "4.2.1", features = ["derive"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
zip = "0.6.4"
